//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Replies
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public int CommentID { get; set; }
        public int UserID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual Comments Comments { get; set; }
        public virtual Users Users { get; set; }
    }
}
